language: python
python: 3.7
dist: xenial
sudo: true

services:
  - docker

before_install:
  - cp env-template .env
  - pip install -r requirements.txt
  - pip install django-test-without-migrations codecov pytest pytest-cov

script:
  - pytest --cov=./

after_success:
  - codecov
