version: '3'
services:

  django:
    build:
      context: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./perfil:/code/perfil
      - ./data:/mnt/data

  notebooks:
    build:
      context: notebooks
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/code

  db:
    image: postgres:10.4-alpine
    environment:
      - PGDATA=./perfil/db
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:4.0.10-alpine
